colors:
  info:
  success:
  warning:
  error:

  #######################################
  # Theme Colors
  # Picked from http://paletton.com/
  #######################################
  primary: 
    darkest: '#005D3A'
    darker: '#007146'
    dark: '#00915A'
    base: '#00BE76'
    light: '#0FCE86'
    lighter: '#3BD198'
    lightest: '#5FDFAF'

  secondary: 
    darkest: '#014555'
    darker: '#03576B'
    dark: '#046F88'
    base: '#148AA6'
    light: '#3399B1'
    lighter: '#59B0C5'
    lightest: '#85CCDD'

  tertiary: 
    darkest: '#29034F'
    darker: '#370669'
    dark: '#460985'
    base: '#5C0DAC'
    light: '#7132B2'
    lighter: '#8A54C1'
    lightest: '#AB84D4'
    
shades:
  inverse: '#2d2d2d'
  alabaster: '#eeeeee'
  white: '#fff'
  black: '#000'